export const RECEIVE_USER_ATTRIBUTES = 'RECEIVE_USER_ATTRIBUTES';
export const RECEIVE_USER = 'RECEIVE_USER';
export const SIGNED_OUT = 'SIGNED_OUT';
export const OAUTH_RESPONSE = 'OAUTH_RESPONSE';
export const USER_READY = 'USER_READY';
